replicaCount: 1

image:
  repository: fentonreid.azurecr.io/aprframework
  tag: #{Build.SourceVersion}#
  pullPolicy: IfNotPresent

ingress:
  host: "aprframework.fentonreid.com"
  tls:
    secretName: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 80

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
